- name: shell
  ansible.builtin.shell: helm repo add 1password https://1password.github.io/connect-helm-charts/

- name: copy
  ansible.builtin.copy:
    src: ./files/cp/1password/values.yaml
    dest: /tmp/1password-values.yaml

- name: copy
  ansible.builtin.copy:
    src: ./files/cp/1password/1password-credentials.json
    dest: /tmp/1password-credentials.json

- name: copy
  ansible.builtin.copy:
    src: ./files/cp/1password/connect_api_token.txt
    dest: /tmp/connect_api_token.txt

- name: shell helm
  ansible.builtin.shell: |
    helm install connect 1password/connect \
      --create-namespace \
      --namespace onepassword \
      --set-file connect.credentials=/tmp/1password-credentials.json \
      --set-file operator.token.value=/tmp/connect_api_token.txt \
      --values /tmp/1password-values.yaml
