- name: shell
  ansible.builtin.shell: helm repo add cilium https://helm.cilium.io/

- name: shell helm
  ansible.builtin.shell: |
    helm install cilium cilium/cilium \
        --version 1.16.1 \
        --namespace kube-system \
        --set kubeProxyReplacement=true \
        --set k8sServiceHost={{ KUBE_API_SERVER_VIP }} \
        --set k8sServicePort=6443
  ignore_errors: true
