- name: shell helm
  ansible.builtin.shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: shell kustomize
  become: true
  ansible.builtin.shell: |
    curl -o /tmp/kustomize -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
    cp -a kustomize /usr/local/bin/kustomize
    chown root:root /usr/local/bin/k9s
    chmod +x /usr/local/bin/kustomize

# - name: shell helm secrets
#   become: true
#   ansible.builtin.shell: |
#     helm plugin install https://github.com/jkroepke/helm-secrets

# - name: shell sops
#   become: true
#   ansible.builtin.shell: |
#     curl -L https://github.com/getsops/sops/releases/download/v3.9.2/sops-v3.9.2.linux.amd64 -o /usr/local/bin/sops
#     chmod +x /usr/local/bin/sops
